### ISSUE TITLE
Респект за длинную арифметику!:)

### ISSUE THREAD

**Issue by LehaIvanov** [Romancikh/Calculator#2]
Мне интересно где ты узнал про этот термин)) Учавствовал в олимпиадах по информатике?

![image](https://github.com/Romancikh/Calculator/assets/13798121/2bae77bd-7fac-41b4-8d25-95403d4e3860)

**Comment by Romancikh** [comment]
Я хотел сложить два числа, но потом понял, что они выходят за пределы int и пришлось подумать над тем, как это решить. В олимпиадах тоже участвовал, но не часто что-то занимал.

**Comment by LehaIvanov** [comment]
Класс! Твою работу принял.
